import { combineReducers } from "redux";
import { categoriesReducer } from "./categoriesReducer";
import { projectsReducer } from "./projectsReducer";
import { projectsApi } from "../services/projectsServices";

export const rootReducer = combineReducers({
  categories: categoriesReducer.reducer,
  projects: projectsReducer,
  // RTK Query autogenerated slice reducer:
  [projectsApi.reducerPath]: projectsApi.reducer
});

export type TRootState = ReturnType<typeof rootReducer>;